### ISSUE TITLE
Fix coverage result response reading

### ISSUE THREAD

**Issue by killy971** [guillaume-nargeot/codecov-haskell#5]
The following change was introduced on codecov server side, apparently by https://github.com/codecov/codecov-python/commit/2eab8f9a5b50dce28c6c187cf41961da5f4cda57: instead of containing the total coverage result as a value, the response to codecov initial post request now contains a url (`wait_url` element in the json content).
Reading this url should return the coverage result in json format as in the example below:

``` json
{"coverage": 42}
```

[Here is the code](https://github.com/codecov/codecov-python/blob/b24066815b056b46f6afdac7051591aead494925/codecov/__init__.py#L221-L241) showing how codecov-python implements the functionality to wait and read the total coverage result.

**Comment by guillaume-nargeot** [comment]
Another change was required to fix the problem: using the `CurlFollowLocation` option in order to follow the link returned by HTTP 301 responses.
This issue is now fixed as of 1c623d515fb1eb1873a3855b1b45f42899e8fb61
